name: "[CI] Continuous Integration"

# Sempre que tiver um commit ou um PR for aberto
on:
    pull_request:
        types: [opened, synchronize]

jobs:
    lint: 
        runs-on: ubuntu-latest
        steps: 
            ## [Commom_CI_Steps]
          - uses: actions/checkout@v3
            ## =================
          - name: "Install depedencies"
            run: "npm install"
          - name: "Lint"
            run: "npm run lint'"
    test:
        runs-on: ubuntu-latest
        container: cypress/browsers:node18.12.0-chrome107
        steps:
            ## [Commom_CI_Steps]
            - uses: actions/checkout@v3
            ## =================
            - name: "Install depedencies"
              run: "npm install"
            - name: "Test - Cypress"
              run: "npm run test"
